name: CI - Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner ton dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # adapte si tu utilises une autre version

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest

      # Étape 4 : Lancer les tests unitaires dans le dossier tests/
      - name: Run tests
        run: pytest -v tests/
